export const cards = [
  {
    cardId: "AAA",
    snapshotId: "BBB",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 1,
    y: 1,
    width: 4,
    height: 3,
  },
  {
    cardId: "AAA",
    snapshotId: "BBA",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 7,
    y: 1,
    width: 4,
    height: 3,
  },
  {
    cardId: "AAA",
    snapshotId: "BBS",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 13,
    y: 1,
    width: 4,
    height: 3,
  },
  {
    cardId: "AAA",
    snapshotId: "BBD",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 1,
    y: 6,
    width: 4,
    height: 3,
  },
  {
    cardId: "AAA",
    snapshotId: "BBF",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 7,
    y: 6,
    width: 4,
    height: 3,
  },
  {
    cardId: "AAA",
    snapshotId: "BBQ",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 13,
    y: 6,
    width: 4,
    height: 3,
  },
  {
    cardId: "AAA",
    snapshotId: "BBW",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 1,
    y: 11,
    width: 4,
    height: 3,
  },
  {
    cardId: "AAA",
    snapshotId: "BBE",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 7,
    y: 11,
    width: 4,
    height: 3,
  },
  {
    cardId: "AAA",
    snapshotId: "BBER",
    colorCode: "#0000FF",
    period: { startDate: "2022-10-12", endDate: "2022-10-14" },
    category: "카테고리",
    todo: [],
    imgUrl: "",
    description: "텍스트입니다.",
    x: 13,
    y: 11,
    width: 4,
    height: 3,
  }
];
